### PR TITLE
Search page redesign

### PR DESCRIPTION
**Pull request by Ambradibi**
Search page:
 - menu
 - tiles

### CODE REVIEW

**Review by cbotsikas — CHANGES_REQUESTED** [review]
Is this the final expected result or we wait for more commits?
image

IMO:
- Filters didn't work for me except Project/Dataset types
- There is an issue with the modals' height (requires page scrolling)
- Modals still have the different colors on top. I would also keep the border colors for the cards too, except the Type label on the card's header
- The hamburger menu for asset details looks like it has wrong class?
image
- It looks like you've partially removed the ability to have both list view and grid view. I thought we said to keep both but use the list view by default. 
- In general, I felt that the UI we currently have looks better, especially the filters
image

**Comment by fabiankirstein** [comment]
@cbotsikas  We decided to go now with a not complete version of this view in order to move forward. I guess the filters are not working because we have to clarify the backend. And we also decided not to have the filter/grid switch, but settle on one option.

**Comment by Ambradibi** [comment]
so do I have to change anything? @FabiApfelkern

**Comment by fabiankirstein** [comment]
We talk about it in the telko

**Comment by Ambradibi** [comment]
10/15 minutes delay due to other meeting, sorry

**Review by cbotsikas — APPROVED** [review]

**Pull request merged**
