### PR TITLE
Manage Filter Type with new search API

### PR DESCRIPTION
**Pull request by jdladiana86**
## Fiter Type

**Management of the "Type filter" with the new search API**

- ElasticService.js: To function globalSearch, I updated the call based on the new API

- mainCtrl.js and searchBarCtrl.js: I added functions for managing the Type filter and for the reset all button

- search.html: I updated the template for the new actions on the Type filter

### CODE REVIEW

**Comment by fabiankirstein** [comment]
@jdladiana86 Thanks! One important thing: Can you enable an empty search? So if I click on the search without keyword a search without "q" is triggered?

**Comment by jdladiana86** [comment]
> @jdladiana86 Thanks! One important thing: Can you enable an empty search? So if I click on the search without keyword a search without "q" is triggered?

Hi @FabiApfelkern , I'm sorry but I didn't understand your request. do you want to enable the search so that an empty "q" appears in the browser URL?

**Comment by cbotsikas** [comment]
No, the opposite. If the user enters the search page without q parameter in the browser URL, the search controller should automatically perform a * search (without adding it to the URL). 
Now, when the user opens the search page without any search term, the url looks like this: `https://bbc6.sics.se:8181/aegis/#!/search` and the page loads empty. Instead It should load all results, similar to opening `https://bbc6.sics.se:8181/aegis/#!/search?q=*` but without the `?q=*` at the URL

**Comment by jdladiana86** [comment]
ok, so when I start an empty search, I return a search with all the results but I don't update the url with q.

**Comment by jdladiana86** [comment]
Hi @FabiApfelkern @cbotsikas, I added the change to this issue

**Comment by fabiankirstein** [comment]
Hi @jdladiana86,

thanks again.
For me the filtering is not working. You are always triggering the empty search now.
It should be the following:
- An empty search is this: https://bbc6.sics.se:8181/hopsworks-api/api/elastic/search (Note no q=*)
- With filter it is like this: https://bbc6.sics.se:8181/hopsworks-api/api/elastic/search?type=proj
- Also multiple filters should be supported: https://bbc6.sics.se:8181/hopsworks-api/api/elastic/search?type=proj&type=ds

Then you can start working on the pagination. I know the API is still missing an information about the total number, but you could for now just set it to 1000. Then you shoudl paginate like this:

- https://bbc6.sics.se:8181/hopsworks-api/api/elastic/search?limit=10&page=1
- ...
- https://bbc6.sics.se:8181/hopsworks-api/api/elastic/search?limit=10&page=4

**Comment by jdladiana86** [comment]
> * Also multiple filters should be supported: https://bbc6.sics.se:8181/hopsworks-api/api/elastic/search?type=proj&type=ds

Hi @FabiApfelkern ,

for this point there is a problem, the filter template was created by Ambra with an "Input Radio Button" tag. Therefore only one selection can be made. Why is it now decided to have multiple selections? if we want to implement this solution I will need a rework. how do i proceed?

**Comment by fabiankirstein** [comment]
I understand. In general we want multiple selections as in every common facetted search. This was then a misunderstanding. But make it low priority and focus and the core functions.

**Comment by jdladiana86** [comment]
Hi @FabiApfelkern ,
I have completed the following changes:
- Type filters also work with empty search
- Multiple type filters can be selected
- Start of pagination filter implementation

**Comment by fabiankirstein** [comment]
@jdladiana86 Thanks!
One important thing. I cannot click on any item to go the details page. E.g. clicking on a project should redirect to the projects page.

**Comment by jdladiana86** [comment]
Hi @FabiApfelkern ,
how do i get the url of the project page?

**Comment by fabiankirstein** [comment]
I don't know. You should look in the original search page. And may be @o-alex can help!?

**Comment by o-alex** [comment]
@FabiApfelkern 
First of, clicking on every element should only allow you to go there if you have access to it. 
As I said before, datasets are searchable by default, but that doesn't mean that you can just go to my dataset if you do not have access to it. At best you will be able to request access to it.
What I can do is add endpoints to retrieve the details about the project/dataset, but if you do not have rights to it, the link won't work and you will still not be redirected to it.

**Comment by o-alex** [comment]
so the have access endpoints are:
https://github.com/aegisbigdata/hopsworks/blob/dev/aegis-web/yo/app/scripts/services/DataSetService.js#L274
https://github.com/aegisbigdata/hopsworks/blob/dev/aegis-web/yo/app/scripts/services/ProjectService.js#L123 

I will also add endpoint to get details about them based on inodeId...

**Comment by fabiankirstein** [comment]
@o-alex Thanks! Sure we should only allow clicking after checking the access. But a first step should be know to actually add links. Even here https://bbc6.sics.se:8181/hopsworks/#!/ I cannot click on any dataset owned by me.

**Comment by fabiankirstein** [comment]
Hey @jdladiana86 We did some updates on the backend. You get now the entire number of items via the aggregation endpoint: https://bbc6.sics.se:8181/hopsworks-api/api/elastic/aggregation

```
    {
        "name": "Count",
        "value": 128773
    },
```
Also we improved the sort by title:
https://bbc6.sics.se:8181/hopsworks-api/api/elastic/search?limit=10&page=4&sort=title&order=asc

**Comment by fabiankirstein** [comment]
What is your current state?

**Comment by jdladiana86** [comment]
Hi @FabiApfelkern ,

I'm trying to figure out how to manage the click on the elements returned by the search. The management of user permissions I find a little tricky. Do I keep working on filters?

**Comment by fabiankirstein** [comment]
@jdladiana86 Please ask @o-alex if you have issues. We only have this week left. What do you mean with "Do I keep working on filters?" ?

**Comment by jdladiana86** [comment]
I'm already feeling with Alex but I can't understand the operations I have to do. For the question of filters, I wanted to find out whether to implement the changes you made on the backend side. Sorting by title.

**Comment by fabiankirstein** [comment]
I understand. Yes you should implement the backend changes. The pagination is very important.

**Pull request merged**
