### PR TITLE
Wallet endpoint

### PR DESCRIPTION
**Pull request by finikm**
Replaces mocked response for Wallet Transactions with actual blockchain transactions.

Console throws exception `Error: [$controller:ctrlreg] The controller with the name 'WalletTransactionsCtrl' is not registered.`, even though the controller is registered in index.js. Not sure if anything else is missing.

### CODE REVIEW

**Comment by fabiankirstein** [comment]
@finikm I added @o-alex as reviewer. I actually don't know what exactly to test here.

**Review by cbotsikas — APPROVED** [review]
LGTM

**Comment by cbotsikas** [comment]
I haven't tested the Java part, @o-alex will you test this or shall we merge?

**Comment by o-alex** [comment]
I also do not have any ways to test it by myself... since it is mostly about interactions with the blockchain.

**Review by fabiankirstein — APPROVED** [review]

**Pull request merged**
