### PR TITLE
Fix: experiments button, jobs and settings redesign

### PR DESCRIPTION
**Pull request by aLe3ouLa**
## Make sure there is no duplicate PR for this issue

* **Please check if the PR meets the following requirements**
- [ ] Adds tests for the submitted changes (for bug fixes & features)
- [ ] Passes the tests
- [ ] HOPSWORKS JIRA issue has been opened for this PR
- [ ] All commits have been squashed down to a single commit

* **Post a link to the associated JIRA issue**

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Review by fabiankirstein — CHANGES_REQUESTED** [review]
Ambra introduced a seperate CSS for our changes (https://github.com/aegisbigdata/hopsworks/blob/dev/aegis-web/yo/app/styles/aegis.css). Could ypu put your CSS in there?

**Comment by aLe3ouLa** [comment]
I move the style in aegis.css, i had a merge conflict by rebasing to dev.

**Comment by fabiankirstein** [comment]
Looks good. Just one basic questions: What features is this PR adding?

**Comment by aLe3ouLa** [comment]
> Looks good. Just one basic questions: What features is this PR adding?

Redesigning Jobs, Kafka, Settings to align the rest of the site and fixes asked on landing page.

**Comment by fabiankirstein** [comment]
Because there are changes in the backend: hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java I guess this from a previous commit?

**Comment by cbotsikas** [comment]
> Because there are changes in the backend: hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java I guess this from a previous commit?

It's due to the rebase Alexandra did. This java change comes from Alex's commits

**Review by fabiankirstein — APPROVED** [review]

**Pull request merged**
