### PR TITLE
Changes needed for open Visualizer upon right clicking a csv file

### PR DESCRIPTION
**Pull request by pitsios-s**
This pull requests addresses the Front-End related changes necessary for issue [#103](https://github.com/aegisbigdata/documentation/issues/103)

Also keep in mind that in order for this to work, you need to have the correponding changes in the Visualizer notebook, which can be found in [this](https://github.com/aegisbigdata/visualizer/commit/6077bb3ed6c83964ffec79b16d97085b66f72675) commit.

### CODE REVIEW

**Review by cbotsikas — CHANGES_REQUESTED** [review]
aegis-web/yo/app/views/datasetsBrowser.html has formatting changes, I can't accept this. please note your required changes, revert the file and apply manually your changes.

**Comment by cbotsikas** [comment]
> aegis-web/yo/app/views/datasetsBrowser.html has formatting changes, I can't accept this. please note your required changes, revert the file and apply manually your changes.

Nevermind. I've seen your changes. I have a different approach that should work for all aegis tools. I'll use your notebook but not the rest. Sorry for the trouble.

**Comment by pitsios-s** [comment]
Hi @cbotsikas , no trouble at all. If you believe that you have a better approach for this, fell free to proceed with that one instead. Just please pay special attention to the way I handle the parameter to the Visualizer notebook in the `jupyterCtrl.js`, because if this changes, I also need to change the notebook once more, which is something I would like to avoid.

Additionally, as you said, the notebook assets in hopsworks-common should be updated with the newer version of the visualizer, in order for every new project to use the latest one.

**Comment by pitsios-s** [comment]
I guess that unless anything more needed, you can ignore and close this PR.

**Comment by cbotsikas** [comment]
I prefer to keep it open as a reminder..

**Comment by cbotsikas** [comment]
closing in favor of https://github.com/aegisbigdata/hopsworks/pull/74

**Pull request closed without merging**
