### PR TITLE
Dataset accessiblity

### PR DESCRIPTION
**Pull request by o-alex**
This PR introduces two new REST endpoints that can be used by the UI to figure out if the logged in user has access to a particular dataset or project.

### CODE REVIEW

**Review by cbotsikas — COMMENTED** [review]
Don't we need this in aegis-web module too?

**Comment by cbotsikas** [comment]
@o-alex any updates on this?

**Comment by o-alex** [comment]
@cbotsikas yes, I pushed now the fix to actually move the javascript endpoints to the aegis module

**Review by cbotsikas — APPROVED** [review]
LGTM

**Pull request merged**
