### PR TITLE
New top header 🌈

### PR DESCRIPTION
**Pull request by cbotsikas**
- Removed the searchBar and reused the original one with some fixes and different styling for in-project pages.
- Updated all pages.
- Removed the mocked user menu from the left sidebar.

https://github.com/aegisbigdata/documentation/issues/164

### CODE REVIEW

**Comment by cbotsikas** [comment]
image

image

**Comment by cbotsikas** [comment]
haven't tested the following:
- aegis-web/yo/app/views/extended-metadata/dataset.html
- aegis-web/yo/app/views/extended-metadata/distribution.html
- aegis-web/yo/app/views/extended-metadata/project.html

**Review by fabiankirstein — CHANGES_REQUESTED** [review]
The search does not work on the project settings page. Is that on purpose?

**Comment by cbotsikas** [comment]
Fixed, good catch

**Comment by cbotsikas** [comment]
Some more pages fixed.

**Pull request merged**
