### PR TITLE
add label to top buttons

### PR DESCRIPTION
**Pull request by Ambradibi**
- Add label to top buttons
[to speed up the work I modified the CSS by adding custom classes at the bottom of the file]

### CODE REVIEW

**Comment by fabiankirstein** [comment]
> 
> 
>     * Add label to top buttons
>       [to speed up the work I modified the CSS by adding custom classes at the bottom of the file]

Is there an issue with an extra CSS file?

**Comment by Ambradibi** [comment]
> > ```
> > * Add label to top buttons
> >   [to speed up the work I modified the CSS by adding custom classes at the bottom of the file]
> > ```
> 
> Is there an issue with an extra CSS file?

no

**Comment by fabiankirstein** [comment]
May be it's better to do it in an extra file to keep the overview.

**Comment by Ambradibi** [comment]
> to keep the overview.

I put it at the bottom of the style.css on purpose

**Comment by fabiankirstein** [comment]
Add what is the purpose?

**Comment by Ambradibi** [comment]
I thought it was easier to review the code

**Comment by fabiankirstein** [comment]
I think it would be better to have your code as seperated as possible from the Hopsworks base code. So we will have it easier with potential fixes etc.

**Comment by Ambradibi** [comment]
ok i will move the code to a separate file

**Review by fabiankirstein — CHANGES_REQUESTED** [review]
Very good, just two things.
image
I think File Actions should look more similar to the other buttons, like with a border etc. 
And please remove the licence comment from Logical Clocks from aegis.css.

**Comment by Ambradibi** [comment]
Done @FabiApfelkern 

Schermata 2019-03-19 alle 10 35 28
Schermata 2019-03-19 alle 10 35 37

**Review by fabiankirstein — APPROVED** [review]

**Pull request merged**
