### PR TITLE
datasets page fix cleaning code

### LINKED ISSUE #175: Datasets page: Allow more room for the title
Allow more room for the title.

image

### LINKED ISSUE #176: Datasets page: fix the double click problem
Fix the double click problem (currently it only clicks on the grey folder icon - it should be able to double click on the entire box), extend the breadcrumb title if possible.

### LINKED ISSUE #178: Datasets page: big gray space on the bottom
There is a big gray space on the bottom.

image

### LINKED ISSUE #179: Datasets page: scrolling issue
Scrolling doesnt work when “Preview is up” and styling is messed up.

image

### LINKED ISSUE #185: Files page: More space in the breadcrumb
More space in the breadcrumb.

image

### PR DESCRIPTION
**Pull request by Ambradibi**
fixes https://github.com/aegisbigdata/documentation/issues/179
fixes https://github.com/aegisbigdata/documentation/issues/178
fixes https://github.com/aegisbigdata/documentation/issues/176
fixes https://github.com/aegisbigdata/documentation/issues/175 
fixes https://github.com/aegisbigdata/documentation/issues/185

### CODE REVIEW

**Review by cbotsikas — CHANGES_REQUESTED** [review]
Everything except to the two .html files looks good. You have replaced the files? There are too many changes, unrelated and you have broken the search box from Datasets.

**Comment by Ambradibi** [comment]
@cbotsikas yes I replaced the lines of code that interested me. Which search box? on the datasets page it works.

**Comment by cbotsikas** [comment]
@Ambradibi the top search was replaced today in the morning. 
image

Please see the changed files [here in github](https://github.com/aegisbigdata/hopsworks/pull/61/files#diff-968eedc6c6f874d57a26274a69dab5cc), there are too many changed line for the .html, i'm sure you don't need all these changes.
image

**Comment by cbotsikas** [comment]
@Ambradibi you can also see what the top search box should do, on the live server.

**Comment by Ambradibi** [comment]
@cbotsikas aligned search bar. Anything else?

**Comment by cbotsikas** [comment]
Both .html files have too many changes. Are you sure all those are required??

**Comment by Ambradibi** [comment]
@cbotsikas yes. With Javier I reset the search and it works. The pages look right and correct according to the requested changes

**Review by cbotsikas — APPROVED** [review]
> @cbotsikas yes. With Javier I reset the search and it works. The pages look right and correct according to the requested changes

Well, you've reformatted the files thus you have so many lines changed. You should never ever mix reformatting and code changes. Those PRs usually are automatically declined.. This time i'll accept it so that we don't lose yet another day..
You've also removed the code you added earlier for the breadcrumb, the one that included the project name. 
image
You need to be more careful!

**Comment by cbotsikas** [comment]
@Ambradibi https://github.com/aegisbigdata/documentation/issues/177 is not fixed here, you forgot the change. You've only reformatted the datasets.html but you didn't change the `newDataSetModal` as you did on [your previous commit](https://github.com/aegisbigdata/hopsworks/pull/53/commits/0fccf407cceea9de40cfd36d22272b52c402a1a1)

I've asked you three times today on this PR to check your .html files. For sure I wouldn't say that 'The pages look right and correct according to the requested changes'
Please be more careful and pay attention to details!

**Pull request merged**
