### PR TITLE
Files page fe fix

### PR DESCRIPTION
**Pull request by Ambradibi**
Files page fix

### CODE REVIEW

**Comment by cbotsikas** [comment]
@Ambradibi which issues is this PR addressing. Is it fixing them?

**Comment by Ambradibi** [comment]
@cbotsikas when I click on **resolve conflicts** it doesn't load the page (I don't know why). Almost certainly it will be on the file aegis.css which is where I put all the changes.

**Comment by cbotsikas** [comment]
The conflicting file is aegis-web/yo/app/views/members.html. It's due to your last commit `merge request`. Why did you do this commit?
I'm asking what are the issue ids, copy paste the url of the issues you're addressing here

**Comment by cbotsikas** [comment]
@Ambradibi what are the issue numbers from https://github.com/aegisbigdata/documentation/issues ?

**Comment by Ambradibi** [comment]
@cbotsikas what would the conflict be? I no longer saw the merge and perhaps in the push I confused the branches. I think it's a single space the error, isn't it? does not load the resolve conflicts page. sorry

**Comment by cbotsikas** [comment]
@Ambradibi I don't care or ask about the conflict. I will resolve it.
I'm asking what are you fixing in this PR? 
What should I check? 
What are the issue numbers?

**Comment by cbotsikas** [comment]
When we merge this, which are the issue that we should close?

**Comment by Ambradibi** [comment]
@cbotsikas the issues are: 
#180
#181
#184
#185

**Comment by cbotsikas** [comment]
> @cbotsikas the issues are:
> #180
> #181
> #184
> @185

thank you. Next time copy and paste the full url address of the issue like:
`https://github.com/aegisbigdata/documentation/issues/180`

so for this PR you have:
https://github.com/aegisbigdata/documentation/issues/180
https://github.com/aegisbigdata/documentation/issues/181
https://github.com/aegisbigdata/documentation/issues/184
https://github.com/aegisbigdata/documentation/issues/185

Apart from the fact that it's making my review process a bit faster, Github also links the PR with the issues and you can see the link in issue's timeline.

**Comment by Ambradibi** [comment]
ok @cbotsikas thanks for all

**Comment by cbotsikas** [comment]
@Ambradibi I can't see how is aegisbigdata/documentation#185 addressed? Can you point me on what you've changed for this issue?

**Comment by cbotsikas** [comment]
Closing in favor of https://github.com/aegisbigdata/hopsworks/pull/58

**Comment by Ambradibi** [comment]
> I can't see how is [aegisbigdata/documentation#185](https://github.com/aegisbigdata/documentation/issues/185) addressed? Can you point me on what you've changed for this issue?


It's a consequence of a change made on the DataSet page (in another branch)

**Comment by cbotsikas** [comment]
Which branch? Is it merged?

**Comment by Ambradibi** [comment]
@cbotsikas not yet.. it's the pull request https://github.com/aegisbigdata/hopsworks/pull/53 (Dataset page fix)

**Pull request closed without merging**
